/*
 * This source file was generated by the Gradle 'init' task
 */
package com.newardassociates.javacalc;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalcTest {
    @Test public void appHasAGreeting() {
        Calc classUnderTest = new Calc();
        assertNotNull("app can instantiate", classUnderTest);
    }
}
